require("joe.set")
require("joe.remap")
require("joe.lazy")
require("joe.colorscheme")

require("joe.plugins.telescope")
require("joe.plugins.harpoon")
require("joe.plugins.lualine")
require("joe.plugins.treesitter")
require("joe.plugins.startup")
require("joe.plugins.gitsigns")
